### ISSUE TITLE
Latest deployment errors

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#291]
When I tried to deploy changes to couchdb using the updated deploy.sh that you made, it crashed with the following error. Perhaps you can spot what the cause is.

$ ./deploy.sh https://admin:password@cococloud.co/coconut-surveillance-zanzibar
Setting global.pouchdb in app/start/coffee to use https://cococloud.co/coconut-surveillance-zanzibar
Browserifying and uglifying
(node:73814) DeprecationWarning: util.print is deprecated. Use console.log instead.
Couchapp pushing to https://admin:password@cococloud.co/coconut-surveillance-zanzibar
2017-03-06 15:17:25 [INFO] Visit your CouchApp here:
https://cococloud.co/coconut-surveillance-zanzibar/_design/analytics/index.html
Pushing all required views
Saving view aggregateCases.coffee
Adding in reduce: alertAlarmCounter__reduce.coffee
Saving view alertAlarmCounter.coffee
Saving view caseCountByWeekAndAge.coffee
Adding in reduce: caseCounter__reduce.coffee
Saving view caseCounter.coffee
Adding in reduce: caseCountIncludingSecondary__reduce.coffee
Saving view caseCountIncludingSecondary.coffee
Saving view caseIDsByDate.coffee
Saving view cases.coffee
Saving view docIDsForUpdating.coffee
Saving view positiveCasesByFacility.coffee
Saving view positiveCasesByFacilityGTE5.coffee
Saving view positiveCasesByFacilityLT5.coffee
Saving view positiveCasesGT5.coffee
Saving view positiveCasesLT5.coffee
Saving view positiveFacilityCasesByDate.coffee
Saving view questions.coffee
Saving view rainfallDataByDateAndLocation.coffee
Saving view resultsByDateWithUserAndCaseId.coffee
Saving view users.coffee
Saving view weeklyDataBySubmitDate.coffee
Adding in reduce: weeklyDataCounter__reduce.coffee
Saving view weeklyDataCounter.coffee
Executing (caching) all required views
Error: Cannot find module 'request'
  at Function.Module._resolveFilename (module.js:440:15)
  at Function.Module._load (module.js:388:25)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/sloo/Projects/RTI/Coconut/coconut-push/__views/executeViews.coffee:1:11)
  at Object.<anonymous> (/Users/sloo/Projects/RTI/Coconut/coconut-push/__views/executeViews.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (node.js:348:7)
  at startup (node.js:140:9)
  at node.js:463:3

**Comment by scloo** [comment]
Issue fixed. Installed module with 
npm install request -g
